ci: check install
Signed-off-by: Artur Troian <troian.ap@gmail.com>

diff --git a/.github/workflows/provider-services.yaml b/.github/workflows/provider-services.yaml
--- a/.github/workflows/provider-services.yaml
+++ b/.github/workflows/provider-services.yaml
@@ -2,6 +2,7 @@ name: provider-sevices
 on:
   repository_dispatch:
     types: provider-services
+
 jobs:
   commit:
     runs-on: ubuntu-latest
@@ -21,10 +22,10 @@ jobs:
           echo "RELEASE_VERSION=${RELEASE_VERSION#v}" >> $GITHUB_ENV
           echo "FORMULA_KEG_ONLY=${FORMULA_KEG_ONLY}" >> $GITHUB_ENV
           if [[ "${FORMULA_KEG_ONLY}" == "true" ]]; then
-              echo "FORMULA_NAME=AKashProviderServicesUnstable" >> $GITHUB_ENV
+              echo "FORMULA_NAME=AkashProviderServicesUnstable" >> $GITHUB_ENV
               echo "FORMULA_FILE=akash-provider-services-unstable.rb" >> $GITHUB_ENV
           else
-              echo "FORMULA_NAME=AKashProviderServices" >> $GITHUB_ENV
+              echo "FORMULA_NAME=AkashProviderServices" >> $GITHUB_ENV
               echo "FORMULA_FILE=akash-provider-services.rb" >> $GITHUB_ENV
           fi
       - name: download checksums
@@ -42,7 +43,7 @@ jobs:
           DARWIN_ALL_CHECKSUM=$(cat provider-services_${{ env.RELEASE_VERSION }}_checksums.txt | grep "provider-services_darwin_all.zip" 2>/dev/null | tr '\t' ' ' | cut -d ' ' -f 1)
           LINUX_AMD64_CHECKSUM=$(cat provider-services_${{ env.RELEASE_VERSION }}_checksums.txt | grep "provider-services_linux_amd64.zip" 2>/dev/null | tr '\t' ' ' | cut -d ' ' -f 1)
           LINUX_ARM64_CHECKSUM=$(cat provider-services_${{ env.RELEASE_VERSION }}_checksums.txt | grep "provider-services_linux_arm64.zip" 2>/dev/null | tr '\t' ' ' | cut -d ' ' -f 1)
-          
+
           echo "DARWIN_ALL_CHECKSUM=${DARWIN_ALL_CHECKSUM}" >> $GITHUB_ENV
           echo "LINUX_AMD64_CHECKSUM=${LINUX_AMD64_CHECKSUM}" >> $GITHUB_ENV
           echo "LINUX_ARM64_CHECKSUM=${LINUX_ARM64_CHECKSUM}" >> $GITHUB_ENV
@@ -56,3 +57,76 @@ jobs:
           default_author: github_actor
           message: 'feat: ${{ env.FORMULA_FILE }} ${{ env.RELEASE_TAG }}'
           push: true
+
+  test-macos:
+    needs: commit
+    runs-on: macos-latest
+    steps:
+      - name: install prerequisites
+        run: |
+          brew update
+          brew install jq
+      - name: set env
+        shell: bash
+        run: |
+          RELEASE_VERSION=${{ github.event.client_payload.tag }}
+          echo "RELEASE_VERSION=${RELEASE_VERSION#v}" >> $GITHUB_ENV
+          if [[ "${{ github.event.client_payload.is_prerelease }}" == "true" ]]; then
+            echo "FORMULA_NAME=akash-provider-services-unstable" >> $GITHUB_ENV
+          else
+            echo "FORMULA_NAME=akash-provider-services" >> $GITHUB_ENV
+          fi
+      - name: install provider-services
+        shell: bash
+        run: |
+          brew tap ovrclk/tap
+          brew install ${{ env.FORMULA_NAME }} --ignore-dependencies
+          installed_version=$(brew info ${{ env.FORMULA_NAME }} --json | jq -r '.[].versions.stable')
+          echo "INSTALLED_VERSION=${installed_version}" >> $GITHUB_ENV
+      - name: validate version
+        shell: bash
+        run: |
+          if [[ "${{ env.RELEASE_VERSION }}" != "${{ env.INSTALLED_VERSION }}" ]]; then
+            echo "::error installed version does not match. expected ${{ env.RELEASE_VERSION }}, installed ${{ env.INSTALLED_VERSION }}"
+            exit 1
+          fi
+
+  test-ubuntu:
+    needs: commit
+    runs-on: ubuntu-latest
+    steps:
+      - name: Set up Homebrew
+        uses: Homebrew/actions/setup-homebrew@master
+      - name: install jq
+        uses: sergeysova/jq-action@v2
+      - name: release version
+        run: |
+          RELEASE_VERSION=${{ github.event.client_payload.tag }}
+          FORMULA_KEG_ONLY=${{ github.event.client_payload.is_prerelease }}
+
+          echo "RELEASE_VERSION=${RELEASE_VERSION#v}" >> $GITHUB_ENV
+          echo "FORMULA_KEG_ONLY=${FORMULA_KEG_ONLY}" >> $GITHUB_ENV
+      - name: set env
+        shell: bash
+        run: |
+          RELEASE_VERSION=${{ github.event.client_payload.tag }}
+          echo "RELEASE_VERSION=${RELEASE_VERSION#v}" >> $GITHUB_ENV
+          if [[ "${{ github.event.client_payload.is_prerelease }}" == "true" ]]; then
+            echo "FORMULA_NAME=akash-provider-services-unstable" >> $GITHUB_ENV
+          else
+            echo "FORMULA_NAME=akash-provider-services" >> $GITHUB_ENV
+          fi
+      - name: install provider-services
+        shell: bash
+        run: |
+          brew tap ovrclk/tap
+          brew install ${{ env.FORMULA_NAME }} --ignore-dependencies
+          installed_version=$(brew info ${{ env.FORMULA_NAME }} --json | jq -r '.[].versions.stable')
+          echo "INSTALLED_VERSION=${installed_version}" >> $GITHUB_ENV
+      - name: validate version
+        shell: bash
+        run: |
+          if [[ "${{ env.RELEASE_VERSION }}" != "${{ env.INSTALLED_VERSION }}" ]]; then
+            echo "::error installed version does not match. expected ${{ env.RELEASE_VERSION }}, installed ${{ env.INSTALLED_VERSION }}"
+            exit 1
+          fi
